-- MySQL Script generated by MySQL Workbench
-- Fri May 24 13:53:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `mydb` ;
-- -----------------------------------------------------
-- Table `mydb`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`localidad` (
  `Codigo_postal` INT NOT NULL,
  `localidad` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo_postal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parcela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parcela` (
  `Num_parcela` INT NOT NULL,
  `localidad_Codigo_postal` INT NOT NULL,
  PRIMARY KEY (`Num_parcela`),
  INDEX `fk_parcela_localidad1_idx` (`localidad_Codigo_postal` ASC) VISIBLE,
  CONSTRAINT `fk_parcela_localidad1`
    FOREIGN KEY (`localidad_Codigo_postal`)
    REFERENCES `mydb`.`localidad` (`Codigo_postal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`arbol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`arbol` (
  `idarbol` VARCHAR(20) NOT NULL,
  `Num_arbol` VARCHAR(45) NOT NULL,
  `Desce` VARCHAR(45) NOT NULL,
  `Objetivo` VARCHAR(45) NULL,
  `Selección` VARCHAR(45) NULL,
  `Variedad` VARCHAR(45) NULL,
  `Padre` VARCHAR(45) NOT NULL,
  `Madre` VARCHAR(45) NOT NULL,
  `parcela_Num_parcela` INT NULL,
  PRIMARY KEY (`idarbol`),
  INDEX `fk_arbol_arbol_idx` (`Padre` ASC) VISIBLE,
  INDEX `fk_arbol_arbol1_idx` (`Madre` ASC) VISIBLE,
  INDEX `fk_arbol_parcela1_idx` (`parcela_Num_parcela` ASC) VISIBLE,
  CONSTRAINT `fk_arbol_arbol`
    FOREIGN KEY (`Padre`)
    REFERENCES `mydb`.`arbol` (`idarbol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arbol_arbol1`
    FOREIGN KEY (`Madre`)
    REFERENCES `mydb`.`arbol` (`idarbol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arbol_parcela1`
    FOREIGN KEY (`parcela_Num_parcela`)
    REFERENCES `mydb`.`parcela` (`Num_parcela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fruto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fruto` (
  `idfruto` INT NOT NULL AUTO_INCREMENT,
  `arbol_idarbol` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idfruto`),
  INDEX `fk_fruto_arbol1_idx` (`arbol_idarbol` ASC) VISIBLE,
  CONSTRAINT `fk_fruto_arbol1`
    FOREIGN KEY (`arbol_idarbol`)
    REFERENCES `mydb`.`arbol` (`idarbol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`observación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`observacion` (
  `idobservacion` INT NOT NULL AUTO_INCREMENT,
  `Año` YEAR NOT NULL,
  `Observacion` TEXT NULL,
  `arbol_idarbol`  VARCHAR(20) NULL ,
  PRIMARY KEY (`idobservacion`),
  INDEX `fk_observacion_arbol1_idx` (`arbol_idarbol` ASC) VISIBLE,
  CONSTRAINT `fk_observacion_arbol1`
    FOREIGN KEY (`arbol_idarbol`)
    REFERENCES `mydb`.`arbol` (`idarbol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`caracter_arbol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`caracter_arbol` (
  `arbol_idarbol` VARCHAR(20) NULL,
  `Año` YEAR NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Valor` VARCHAR(255) NULL,
  `Tipo_caracter` ENUM('Fruto', 'Produccion', 'Genetico', 'Fenologico', 'Compatibilidad') NOT NULL,
  `idcaracter_arbol` INT NOT NULL AUTO_INCREMENT,
  
  PRIMARY KEY (`idcaracter_arbol`),
  INDEX `fk_caracter_arbol1_idx` (`arbol_idarbol` ASC) VISIBLE,
  CONSTRAINT `fk_caracter_arbol1`
    FOREIGN KEY (`arbol_idarbol`)
    REFERENCES `mydb`.`arbol` (`idarbol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`caracter_fruto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`caracter_fruto` (
  `idcaracter_fruto` INT NOT NULL AUTO_INCREMENT,
  `Año` YEAR NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Tipo_dato` VARCHAR(45) NOT NULL,
  `Tipo_caracter` ENUM('Fruto', 'Producción', 'Genético', 'Fenológico', 'Compatibilidad') NOT NULL,
  `Valor` INT NULL,
  `arbol_idarbol` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idcaracter_fruto`),
  INDEX `fk_caracter_fruto_arbol1_idx` (`arbol_idarbol` ASC) VISIBLE,
  CONSTRAINT `fk_caracter_fruto_arbol1`
    FOREIGN KEY (`arbol_idarbol`)
    REFERENCES `mydb`.`arbol` (`idarbol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
